In [2]:
import math
import pandas as pd
import numpy as np

In [3]:
#load data from excel file using pip or conda install xlrd
#install pip 
#install conda
#install xlrd

df = pd.read_csv('heart_data1.csv', index_col=0)
df.head()

,age,sex,location,chest pain,resting blood pressure,cholesterol,fasting blood sugar,Resting ECG,max heart rate (thalch),exang (angina),oldpeak,slope,ca,thal,num
ID,,,,,,,,,,,,,,,
1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0
5,56,Male,Cleveland,atypical angina,120.0,236.0,False,normal,178.0,False,0.8,upsloping,0.0,normal,0

In [6]:
#descrive data
df.describe()

,age,resting blood pressure,cholesterol,max heart rate (thalch),oldpeak,ca,num
count,676.000000,643.000000,650.000000,643.000000,640.000000,223.000000,676.000000
mean,51.715976,131.068429,214.946154,141.838258,0.645938,0.399103,0.392012
std,9.276611,18.137884,99.125025,25.059654,0.900312,0.733619,0.488561
min,28.000000,80.000000,0.000000,69.000000,-2.600000,0.000000,0.000000
25%,45.000000,120.000000,195.000000,122.000000,0.000000,0.000000,0.000000
50%,53.000000,130.000000,228.500000,143.000000,0.000000,0.000000,0.000000
75%,58.000000,140.000000,269.000000,160.500000,1.200000,1.000000,1.000000
max,76.000000,200.000000,603.000000,202.000000,5.000000,3.000000,1.000000

In [7]:
#check for null values
df.isnull().sum()

age                          0
sex                          0
location                     0
chest pain                   0
resting blood pressure      33
cholesterol                 26
fasting blood sugar         54
Resting ECG                  2
max heart rate (thalch)     33
exang (angina)              33
oldpeak                     36
slope                      260
ca                         453
thal                       383
num                          0
dtype: int64

In [10]:
#check for duplicates
df.duplicated().sum()

#drop duplicates
df.drop_duplicates(inplace=True)
df

,age,sex,location,chest pain,resting blood pressure,cholesterol,fasting blood sugar,Resting ECG,max heart rate (thalch),exang (angina),oldpeak,slope,ca,thal,num
ID,,,,,,,,,,,,,,,
1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0
5,56,Male,Cleveland,atypical angina,120.0,236.0,False,normal,178.0,False,0.8,upsloping,0.0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,62,Male,VA Long Beach,asymptomatic,158.0,170.0,False,st-t abnormality,138.0,True,0.0,NaN,NaN,NaN,1
673,54,Female,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,NaN,NaN,1
674,62,Male,VA Long Beach,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,0
675,58,Male,VA Long Beach,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
676,62,Male,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,NaN,NaN,1

In [18]:
#fill numerical columns with median values: resting blood pressure, cholesterol, max heart rate, oldpeak,ca
df['resting blood pressure'] = df['resting blood pressure'].fillna(df['resting blood pressure'].median())
df['cholesterol'] = df['cholesterol'].fillna(df['cholesterol'].median())
df['max_heart_rate'] = df['max_heart_rate'].fillna(df['max_heart_rate'].median())
df['oldpeak'] = df['oldpeak'].fillna(df['oldpeak'].median())
df['ca'] = df['ca'].fillna(df['ca'].median())
df

KeyError: 'resting blood pressure'